# Generated by Django 6.0.7 on 2026-08-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
