# Generated by Django 6.0.7 on 2026-08-10 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_short_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('discounted_price__isnull', True), ('discounted_price__lt', models.F('price')), _connector='OR'), name='discounted_price_less_than_price'),
        ),
    ]
