# Generated by Django 6.0.7 on 2026-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wishlist_wishlistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
