# Generated by Django 6.0.7 on 2026-08-19 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_display_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product_relations', to='products.product', verbose_name='product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_relations', to='products.product', verbose_name='related product')),
            ],
            options={
                'verbose_name': 'product related product',
                'verbose_name_plural': 'product related products',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_from_products', through='products.ProductRelatedProduct', to='products.product', verbose_name='related products'),
        ),
        migrations.AddConstraint(
            model_name='productrelatedproduct',
            constraint=models.UniqueConstraint(fields=('product', 'related_product'), name='unique_product_related_product'),
        ),
        migrations.AddConstraint(
            model_name='productrelatedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('product', models.F('related_product')), _negated=True), name='product_cannot_be_related_to_itself'),
        ),
    ]
