# Generated by Django 6.0.7 on 2026-08-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productrelatedproduct_product_related_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='weight',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='volume',
            field=models.PositiveIntegerField(default=0, help_text='Volume in milliliter.', verbose_name='Volume (ml)'),
        ),
    ]
