# Generated by Django 6.0.7 on 2026-08-20 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productvariant_weight_productvariant_volume'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bundleitem',
            name='unique_bundle_variant',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='product',
        ),
        migrations.AddField(
            model_name='bundle',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='variant',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='products.productvariant', verbose_name='variant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BundleItem',
        ),
    ]
