# Generated by Django 6.0.7 on 2026-08-26 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_bundleitem_unique_bundle_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='volume',
            field=models.PositiveIntegerField(help_text='Volume in milliliter.', verbose_name='Volume (ml)'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'volume'), name='unique_volume_per_product'),
        ),
    ]
