# Generated by Django 6.0.7 on 2026-09-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productvariant_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('starts_at', models.DateTimeField(verbose_name='starts_at')),
                ('ends_at', models.DateTimeField(verbose_name='ends_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('products', models.ManyToManyField(blank=True, related_name='discount_campaigns', to='products.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Discount Campaign',
                'verbose_name_plural': 'Discount Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
