# Generated by Django 6.0.7 on 2026-09-19 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_discountcampaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcampaign',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AddField(
            model_name='discountcampaign',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='discountcampaign',
            name='singleton_key',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
