# Generated by Django 6.0.8 on 2026-09-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_wishlist_stock_notify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['-created_at'], 'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['-created_at'], 'verbose_name': 'مقدار ویژگی', 'verbose_name_plural': 'مقادیر ویژگی'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['title'], 'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'بسته', 'verbose_name_plural': 'بسته\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='hairproblem',
            options={'ordering': ['title'], 'verbose_name': 'مشکل مو', 'verbose_name_plural': 'مشکلات مو'},
        ),
        migrations.AlterModelOptions(
            name='hairtype',
            options={'ordering': ['title'], 'verbose_name': 'نوع مو', 'verbose_name_plural': 'انواع مو'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی\u200cهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AlterModelOptions(
            name='productrelatedproduct',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'محصول مرتبط', 'verbose_name_plural': 'محصولات مرتبط'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-created_at'], 'verbose_name': 'تنوع محصول', 'verbose_name_plural': 'تنوع\u200cهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='variantattribute',
            options={'ordering': ['-created_at'], 'verbose_name': 'ویژگی تنوع', 'verbose_name_plural': 'ویژگی\u200cهای تنوع'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'علاقه\u200cمندی', 'verbose_name_plural': 'علاقه\u200cمندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'آیتم علاقه\u200cمندی', 'verbose_name_plural': 'آیتم\u200cهای علاقه\u200cمندی'},
        ),
        migrations.AlterModelOptions(
            name='wishliststocknotify',
            options={'verbose_name': 'اطلاع موجودی', 'verbose_name_plural': 'اطلاع\u200cهای موجودی'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/brands/logos', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/categories', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='hairproblem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hair/problems', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='hairproblem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='hairproblem',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='hairproblem',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='hairtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hair/types', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='hairtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='hairtype',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='hairtype',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_problems',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.hairproblem', verbose_name='مشکل مو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.hairtype', verbose_name='نوع مو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_from_products', through='products.ProductRelatedProduct', to='products.product', verbose_name='محصولات مرتبط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discounted_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف\u200cخورده'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='volume',
            field=models.PositiveIntegerField(default=0, help_text='Volume in milliliter.', verbose_name='حجم (میلی\u200cلیتر)'),
        ),
    ]
