# Generated by Django 6.0.7 on 2026-09-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_categories_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='products.productvariant', verbose_name='تنوع محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_in_special_offer',
            field=models.BooleanField(default=False, help_text='همراه با قیمت تخفیف\u200cخورده روی واریانت\u200cها قابل تنظیم است (حتی هنگام ایجاد محصول). فقط محصولاتی که حداقل یک واریانت فعال با قیمت تخفیف\u200cخورده دارند در پیشنهاد ویژه می\u200cمانند.', verbose_name='نمایش در پیشنهاد ویژه'),
        ),
    ]
