# Generated by Django 6.0.7 on 2026-09-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0013_alter_productvariant_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbundle',
            name='bundle_quantity',
            field=models.PositiveIntegerField(default=3, verbose_name='bundle quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderbundle',
            name='variant',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='order_bundles', to='products.productvariant', verbose_name='variant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='total_price',
            field=models.PositiveBigIntegerField(verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='unit_price',
            field=models.PositiveBigIntegerField(verbose_name='unit price'),
        ),
    ]
