# Generated by Django 6.0.7 on 2026-09-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='public number'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='tracking code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting payment'), ('payment_rejected', 'Payment rejected'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='waiting_payment', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting payment'), ('payment_rejected', 'Payment rejected'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('expired', 'Expired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_payment', 'Waiting payment'), ('payment_rejected', 'Payment rejected'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('expired', 'Expired')], max_length=30),
        ),
    ]
