# Generated by Django 6.0.7 on 2026-09-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_tracking_code_alter_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('payment_rejected', 'Payment rejected'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='created', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Created'), ('payment_rejected', 'Payment rejected'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('expired', 'Expired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(choices=[('created', 'Created'), ('payment_rejected', 'Payment rejected'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('expired', 'Expired')], max_length=30),
        ),
    ]
