# Generated by Django 6.0.7 on 2026-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_unit_price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
