# Generated by Django 6.0.8 on 2026-09-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_sync_model_state'),
        ('orders', '0007_order_public_number_and_waiting_payment'),
        ('products', '0017_sync_model_state'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='orderbundle',
            options={'verbose_name': 'بسته سفارش', 'verbose_name_plural': 'بسته\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'تاریخچه وضعیت سفارش', 'verbose_name_plural': 'تاریخچه\u200cهای وضعیت سفارش'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آماده\u200cسازی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت محصولات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=255, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.shippingmethod', verbose_name='روش ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='total_price',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='orderbundle',
            name='unit_price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='full_address',
            field=models.TextField(verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderbundle', verbose_name='بسته سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='original_unit_price',
            field=models.PositiveIntegerField(verbose_name='قیمت واحد اصلی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(max_length=255, verbose_name='عنوان محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='province',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='تنوع محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_sku',
            field=models.CharField(max_length=100, verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_order_statuses', to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'ایجاد شده'), ('waiting_payment', 'در انتظار پرداخت'), ('payment_rejected', 'پرداخت رد شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده'), ('expired', 'منقضی شده')], max_length=30, verbose_name='وضعیت جدید'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(choices=[('created', 'ایجاد شده'), ('waiting_payment', 'در انتظار پرداخت'), ('payment_rejected', 'پرداخت رد شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده'), ('expired', 'منقضی شده')], max_length=30, verbose_name='وضعیت قبلی'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='reason',
            field=models.TextField(blank=True, verbose_name='دلیل'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('system', 'System'), ('customer', 'Customer')], default='system', max_length=30, verbose_name='منبع'),
        ),
    ]
