# Generated by Django 6.0.7 on 2026-09-21 20:44

from django.db import migrations, models


def remap_created_status(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderStatusHistory = apps.get_model("orders", "OrderStatusHistory")

    Order.objects.filter(status="created").update(status="waiting_payment")
    OrderStatusHistory.objects.filter(old_status="created").update(
        old_status="waiting_payment",
    )
    OrderStatusHistory.objects.filter(new_status="created").update(
        new_status="waiting_payment",
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_sync_model_state"),
    ]

    operations = [
        migrations.RunPython(remap_created_status, noop_reverse),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting_payment", "در انتظار پرداخت"),
                    ("payment_rejected", "پرداخت رد شده"),
                    ("preparing", "در حال آماده‌سازی"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل شده"),
                    ("canceled", "لغو شده"),
                    ("expired", "منقضی شده"),
                ],
                default="waiting_payment",
                max_length=30,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("waiting_payment", "در انتظار پرداخت"),
                    ("payment_rejected", "پرداخت رد شده"),
                    ("preparing", "در حال آماده‌سازی"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل شده"),
                    ("canceled", "لغو شده"),
                    ("expired", "منقضی شده"),
                ],
                max_length=30,
                verbose_name="وضعیت جدید",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("waiting_payment", "در انتظار پرداخت"),
                    ("payment_rejected", "پرداخت رد شده"),
                    ("preparing", "در حال آماده‌سازی"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل شده"),
                    ("canceled", "لغو شده"),
                    ("expired", "منقضی شده"),
                ],
                max_length=30,
                verbose_name="وضعیت قبلی",
            ),
        ),
    ]
