# Generated by Django 6.0.7 on 2026-09-21 20:54

from django.db import migrations, models


def backfill_order_carrier(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.select_related("shipping_method").iterator():
        if order.carrier:
            continue
        method = order.shipping_method
        if method and method.carrier:
            order.carrier = method.carrier
            order.save(update_fields=["carrier"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_order_status_created"),
        ("shipping", "0004_add_shipping_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.CharField(
                blank=True,
                choices=[("post", "پست"), ("tipax", "تیپاکس")],
                default="",
                max_length=16,
                verbose_name="حامل",
            ),
        ),
        migrations.RunPython(backfill_order_carrier, noop_reverse),
    ]
