# Generated by Django 6.0.7 on 2026-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_delivery_confirm_sms_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='source',
            field=models.CharField(choices=[('admin', 'ادمین'), ('system', 'سیستم'), ('customer', 'مشتری')], default='system', max_length=30, verbose_name='منبع'),
        ),
    ]
