# Generated by Django 6.0.7 on 2026-09-09 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('discounts', '0003_discount_applies_to_discounted_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='discounts.discount', verbose_name='discount'),
        ),
    ]
