# Generated by Django 6.0.7 on 2026-08-03 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('title', models.CharField(help_text='For example: home, work, parents', max_length=100, verbose_name='title')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='receiver name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('province', models.CharField(max_length=100, verbose_name='province')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('address', models.TextField(verbose_name='address')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user')],
            },
        ),
    ]
