# Generated by Django 6.0.7 on 2026-09-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheTable',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'cache_table',
                'managed': False,
            },
        ),
    ]
