# Generated by Django 6.0.7 on 2026-08-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customersatisfaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
            ],
            options={
                'verbose_name': 'FAQCategory',
                'verbose_name_plural': 'FAQCategories',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='customersatisfaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='customersatisfaction',
            name='image',
            field=models.ImageField(upload_to='media/customer/satisfaction', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='customersatisfaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='home.faqcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
