# Generated by Django 6.0.7 on 2026-08-11 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_faqcategory_alter_customersatisfaction_created_at_and_more'),
        ('products', '0006_productvariant_discounted_price_less_than_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('custom', 'Custom URL'), ('none', 'No link')], max_length=20, verbose_name='link type'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('image', models.ImageField(upload_to='media/home/slider', verbose_name='image')),
                ('link_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category')], max_length=20, verbose_name='link type')),
                ('custom_url', models.URLField(blank=True, max_length=500, verbose_name='custom URL')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='products.category', verbose_name='category')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
