# Generated by Django 6.0.7 on 2026-08-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_banner_link_type_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='custom_url',
        ),
    ]
