# Generated by Django 6.0.7 on 2026-09-05 18:48

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_slider_custom_url'),
        ('products', '0013_alter_productvariant_volume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AlterField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(default=1, help_text='1 = first hero, 2 = second hero, 3 = third hero', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='hero position'),
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(fields=('display_order',), name='unique_banner_display_order'),
        ),
    ]
