# Generated by Django 6.0.7 on 2026-09-11 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_banner_title_alter_banner_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(default=1, help_text='1 = first hero, 2 = second hero, 3 = third hero, 4 = fourth hero, 5 = fifth hero', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='hero position'),
        ),
    ]
