# Generated by Django 6.0.8 on 2026-09-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_banner_display_order'),
        ('products', '0017_sync_model_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
        migrations.AlterModelOptions(
            name='customersatisfaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'رضایت مشتری', 'verbose_name_plural': 'رضایت مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'پرسش متداول', 'verbose_name_plural': 'پرسش\u200cهای متداول'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'دسته\u200cبندی پرسش', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای پرسش'},
        ),
        migrations.AlterModelOptions(
            name='homeabout',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='custom_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='لینک سفارشی'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='media/home/banner', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_type',
            field=models.CharField(choices=[('product', 'محصول'), ('category', 'دسته\u200cبندی'), ('custom', 'لینک سفارشی'), ('none', 'بدون لینک')], max_length=20, verbose_name='نوع لینک'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='media/home/slider', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link_type',
            field=models.CharField(choices=[('product', 'محصول'), ('category', 'دسته\u200cبندی')], max_length=20, verbose_name='نوع لینک'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='products.product', verbose_name='محصول'),
        ),
    ]
