# Generated by Django 6.0.7 on 2026-08-26 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_alter_productvariant_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20, verbose_name='gender')),
                ('duration', models.CharField(choices=[('less_than_month', 'Less than a month'), ('one_to_three_months', 'One to three months'), ('more_than_three_months', 'More than three months')], max_length=50, verbose_name='duration')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('hair_problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_requests', to='products.hairproblem', verbose_name='hair problem')),
            ],
            options={
                'verbose_name': 'consultation request',
                'verbose_name_plural': 'consultation requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_recommendations', to='products.product', verbose_name='product')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='consultations.consultationrequest', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'consultation recommendation',
                'verbose_name_plural': 'consultation recommendations',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('consultation', 'product'), name='unique_consultation_recommendation')],
            },
        ),
    ]
