# Generated by Django 6.0.7 on 2026-08-26 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('products', '0013_alter_productvariant_volume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationGuestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'consultation guest access',
                'verbose_name_plural': 'consultation guest accesses',
            },
        ),
        migrations.AlterModelOptions(
            name='consultationrecommendation',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'consultation recommendation', 'verbose_name_plural': 'consultation recommendations'},
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_recommendations', to='products.product', verbose_name='consultation recommendations'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='guest_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='consultations.consultationguestaccess', verbose_name='guest access'),
        ),
    ]
