# Generated by Django 6.0.7 on 2026-08-26 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationguestaccess_and_more'),
        ('products', '0013_alter_productvariant_volume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'guest identity',
                'verbose_name_plural': 'guest identities',
            },
        ),
        migrations.CreateModel(
            name='GuestOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='guest_access',
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_recommendations', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GuestDeviceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='last used at')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_accesses', to='consultations.guestidentity', verbose_name='guest')),
            ],
            options={
                'verbose_name': 'guest device access',
                'verbose_name_plural': 'guest device accesses',
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='consultations.guestidentity', verbose_name='guest'),
        ),
        migrations.AddConstraint(
            model_name='consultationrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('guest__isnull', True)), models.Q(('user__isnull', True), ('guest__isnull', False)), _connector='OR'), name='consultation_has_exactly_one_owner'),
        ),
        migrations.AddField(
            model_name='guestotp',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='consultations.guestidentity'),
        ),
        migrations.DeleteModel(
            name='ConsultationGuestAccess',
        ),
    ]
