# Generated by Django 6.0.7 on 2026-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_guestidentity_guestotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='request_phone_consultation',
            field=models.BooleanField(default=False, verbose_name='phone consultation'),
        ),
    ]
