# Generated by Django 6.0.7 on 2026-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultationrequest_request_phone_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
