# Generated by Django 6.0.7 on 2026-09-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_consultationrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrecommendation',
            options={'ordering': ['display_order', 'created_at']},
        ),
    ]
