# Generated by Django 6.0.7 on 2026-09-05 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_alter_consultationrecommendation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdeviceaccess',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='expires at'),
            preserve_default=False,
        ),
    ]
