# Generated by Django 6.0.7 on 2026-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_guestdeviceaccess_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecommendation',
            name='usage_instruction',
            field=models.TextField(blank=True, default='', verbose_name='usage instruction'),
        ),
    ]
