# Generated by Django 6.0.7 on 2026-09-08 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_consultationrecommendation_usage_instruction'),
        ('products', '0013_alter_productvariant_volume_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consultationrecommendation',
            name='unique_consultation_recommendation',
        ),
        migrations.AddField(
            model_name='consultationrecommendation',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_recommendations', to='products.bundle', verbose_name='bundle'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_recommendations', to='products.product', verbose_name='product'),
        ),
        migrations.AddConstraint(
            model_name='consultationrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('bundle__isnull', True)), models.Q(('product__isnull', True), ('bundle__isnull', False)), _connector='OR'), name='recommendation_has_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='consultationrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('consultation', 'product'), name='unique_consultation_product_recommendation'),
        ),
        migrations.AddConstraint(
            model_name='consultationrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('bundle__isnull', False)), fields=('consultation', 'bundle'), name='unique_consultation_bundle_recommendation'),
        ),
    ]
