# Generated by Django 6.0.7 on 2026-09-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_remove_consultationrecommendation_unique_consultation_recommendation_and_more'),
        ('products', '0013_alter_productvariant_volume_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consultationrecommendation',
            name='recommendation_has_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='consultationrecommendation',
            name='unique_consultation_product_recommendation',
        ),
        migrations.AddField(
            model_name='consultationrecommendation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_recommendations', to='products.productvariant', verbose_name='product variant'),
        ),
        migrations.AddConstraint(
            model_name='consultationrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('variant__isnull', False), ('bundle__isnull', True)), models.Q(('variant__isnull', True), ('bundle__isnull', False)), _connector='OR'), name='recommendation_has_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='consultationrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('consultation', 'variant'), name='unique_consultation_variant_recommendation'),
        ),
        migrations.RemoveField(
            model_name='consultationrecommendation',
            name='product',
        ),
    ]
