# Generated by Django 6.0.7 on 2026-09-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_remove_consultationrecommendation_recommendation_has_exactly_one_target_and_more'),
        ('products', '0013_alter_productvariant_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRecommendationPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'consultation recommendation pack',
                'verbose_name_plural': 'consultation recommendation packs',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRecommendationPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'consultation recommendation pack item',
                'verbose_name_plural': 'consultation recommendation pack items',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='consultationrecommendation',
            name='unique_consultation_bundle_recommendation',
        ),
        migrations.RemoveConstraint(
            model_name='consultationrecommendation',
            name='recommendation_has_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='consultationrecommendation',
            name='unique_consultation_variant_recommendation',
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_recommendations', to='products.productvariant', verbose_name='product variant'),
        ),
        migrations.AddConstraint(
            model_name='consultationrecommendation',
            constraint=models.UniqueConstraint(fields=('consultation', 'variant'), name='unique_consultation_variant_recommendation'),
        ),
        migrations.AddField(
            model_name='consultationrecommendationpack',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_packs', to='consultations.consultationrequest', verbose_name='consultation'),
        ),
        migrations.AddField(
            model_name='consultationrecommendationpackitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultations.consultationrecommendationpack', verbose_name='pack'),
        ),
        migrations.AddField(
            model_name='consultationrecommendationpackitem',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_items', to='consultations.consultationrecommendation', verbose_name='recommendation'),
        ),
        migrations.RemoveField(
            model_name='consultationrecommendation',
            name='bundle',
        ),
        migrations.AddConstraint(
            model_name='consultationrecommendationpackitem',
            constraint=models.UniqueConstraint(fields=('pack', 'recommendation'), name='unique_pack_recommendation'),
        ),
    ]
