# Generated by Django 6.0.7 on 2026-09-20 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_consultationrecommendationpack_and_more'),
        ('products', '0017_sync_model_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست مشاوره', 'verbose_name_plural': 'درخواست\u200cهای مشاوره'},
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='duration',
            field=models.CharField(choices=[('less_than_month', 'کمتر از یک ماه'), ('one_to_three_months', 'یک تا سه ماه'), ('more_than_three_months', 'بیشتر از سه ماه')], max_length=50, verbose_name='مدت مشکل'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='gender',
            field=models.CharField(choices=[('female', 'زن'), ('male', 'مرد')], max_length=20, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='consultations.guestidentity', verbose_name='مهمان'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='hair_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_requests', to='products.hairproblem', verbose_name='مشکل مو'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_phone_consultation',
            field=models.BooleanField(default=False, verbose_name='درخواست مشاوره تلفنی'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
