# Generated by Django 6.0.7 on 2026-09-21 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_sync_persian_labels'),
        ('products', '0018_product_show_in_special_offer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrecommendation',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'پیشنهاد محصول مشاوره', 'verbose_name_plural': 'پیشنهادهای محصول مشاوره'},
        ),
        migrations.AlterModelOptions(
            name='consultationrecommendationpack',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'پک پیشنهادی مشاوره', 'verbose_name_plural': 'پک\u200cهای پیشنهادی مشاوره'},
        ),
        migrations.AlterModelOptions(
            name='consultationrecommendationpackitem',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'آیتم پک مشاوره', 'verbose_name_plural': 'آیتم\u200cهای پک مشاوره'},
        ),
        migrations.AlterModelOptions(
            name='guestdeviceaccess',
            options={'verbose_name': 'دسترسی دستگاه مهمان', 'verbose_name_plural': 'دسترسی\u200cهای دستگاه مهمان'},
        ),
        migrations.AlterModelOptions(
            name='guestidentity',
            options={'verbose_name': 'هویت مهمان', 'verbose_name_plural': 'هویت\u200cهای مهمان'},
        ),
        migrations.AlterModelOptions(
            name='guestotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'کد تأیید مهمان', 'verbose_name_plural': 'کدهای تأیید مهمان'},
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='consultations.consultationrequest', verbose_name='مشاوره'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='usage_instruction',
            field=models.TextField(blank=True, default='', verbose_name='دستور مصرف'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_recommendations', to='products.productvariant', verbose_name='واریانت محصول'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpack',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_packs', to='consultations.consultationrequest', verbose_name='مشاوره'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpack',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpack',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpack',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpackitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpackitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpackitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultations.consultationrecommendationpack', verbose_name='پک'),
        ),
        migrations.AlterField(
            model_name='consultationrecommendationpackitem',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_items', to='consultations.consultationrecommendation', verbose_name='پیشنهاد'),
        ),
        migrations.AlterField(
            model_name='guestdeviceaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='guestdeviceaccess',
            name='expires_at',
            field=models.DateTimeField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='guestdeviceaccess',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_accesses', to='consultations.guestidentity', verbose_name='مهمان'),
        ),
        migrations.AlterField(
            model_name='guestdeviceaccess',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین استفاده'),
        ),
        migrations.AlterField(
            model_name='guestdeviceaccess',
            name='token',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='توکن'),
        ),
        migrations.AlterField(
            model_name='guestidentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='guestidentity',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='guestidentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
