# Generated by Django 6.0.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0016_seed_consultation_faqs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationPageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("intro", "معرفی بالای صفحه (متن کنار عکس)"),
                            ("cta", "بخش پایین صفحه (متن و عکس)"),
                        ],
                        help_text=(
                            "intro = عنوان/توضیح/عکس بالای فرم؛ "
                            "cta = عنوان/توضیح/عکس پایین صفحه."
                        ),
                        max_length=20,
                        unique=True,
                        verbose_name="بخش",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="متن کنار عکس")),
                (
                    "image",
                    models.ImageField(
                        help_text=(
                            "intro: حدود ۱۲۰۰×۹۰۰ (نسبت ۴:۳). "
                            "cta: حدود ۱۹۲۰×۷۷۰ (نسبت حدود ۵:۲)."
                        ),
                        upload_to="media/consultations/page",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "محتوای صفحه مشاوره",
                "verbose_name_plural": "محتوای صفحه مشاوره",
                "ordering": ["section"],
            },
        ),
    ]
