# Generated by Django 6.0.7 on 2026-09-20 19:26

import apps.payments.models.payment_intent
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shop_api_gaps'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDestinationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('card_number', models.CharField(max_length=19, verbose_name='card number')),
                ('bank_name', models.CharField(max_length=100, verbose_name='bank name')),
                ('holder_name', models.CharField(max_length=150, verbose_name='holder name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'payment destination card',
                'verbose_name_plural': 'payment destination cards',
                'ordering': ['-is_active', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('token', models.CharField(default=apps.payments.models.payment_intent.generate_payment_intent_token, editable=False, max_length=64, unique=True, verbose_name='token')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('receipt_submitted', 'Receipt submitted'), ('under_review', 'Under review'), ('manual_review', 'Manual review'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('refunded', 'Refunded')], db_index=True, default='pending_payment', max_length=32, verbose_name='status')),
                ('payable_amount', models.PositiveBigIntegerField(verbose_name='payable amount (toman)')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='media/payments/receipts', verbose_name='receipt image')),
                ('receipt_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='receipt uploaded at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='idempotency key')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('destination_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='payments.paymentdestinationcard', verbose_name='destination card')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='orders.order', verbose_name='order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'payment intent',
                'verbose_name_plural': 'payment intents',
                'ordering': ['-created_at'],
            },
        ),
    ]
