# Generated by Django 6.0.7 on 2026-09-14 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderbundle_bundle_quantity_orderbundle_variant_and_more'),
        ('payments', '0002_remove_payment_gateway_payment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='card number')),
                ('display_pan', models.CharField(max_length=32, verbose_name='display pan')),
                ('masked_pan', models.CharField(max_length=32, verbose_name='masked pan')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'destination card',
                'verbose_name_plural': 'destination cards',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public token')),
                ('base_amount_rial', models.PositiveBigIntegerField(verbose_name='base amount rial')),
                ('unique_suffix', models.PositiveSmallIntegerField(verbose_name='unique suffix')),
                ('adjustment_discount', models.PositiveIntegerField(default=0, verbose_name='adjustment discount')),
                ('payable_amount_rial', models.PositiveBigIntegerField(verbose_name='payable amount rial')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('receipt_submitted', 'Receipt submitted'), ('under_review', 'Under review'), ('manual_review', 'Manual review'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending_payment', max_length=32, verbose_name='status')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('bank_reference', models.CharField(blank=True, max_length=255, verbose_name='bank reference')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('destination_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='payments.destinationcard', verbose_name='destination card')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='orders.order', verbose_name='order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'payment intent',
                'verbose_name_plural': 'payment intents',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('file', models.FileField(upload_to='payments/receipts/%Y/%m/', verbose_name='file')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='original name')),
                ('mime_type', models.CharField(max_length=100, verbose_name='mime type')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='file size')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('idempotency_key', models.CharField(max_length=255, verbose_name='idempotency key')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.paymentintent', verbose_name='payment intent')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual review')], max_length=32, verbose_name='decision')),
                ('bank_reference', models.CharField(blank=True, max_length=255, verbose_name='bank reference')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reviews', to=settings.AUTH_USER_MODEL, verbose_name='admin')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='payments.paymentintent', verbose_name='payment intent')),
            ],
            options={
                'verbose_name': 'payment review',
                'verbose_name_plural': 'payment reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'created_at'], name='payment_intent_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['expires_at'], name='payment_intent_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_payment', 'receipt_submitted', 'under_review', 'manual_review'))), fields=('destination_card', 'payable_amount_rial'), name='unique_active_payment_amount_per_card'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_payment', 'receipt_submitted', 'under_review', 'manual_review'))), fields=('order',), name='unique_active_payment_intent_per_order'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['payment_intent', 'is_active'], name='payment_receipt_intent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['sha256'], name='payment_receipt_sha256_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.UniqueConstraint(fields=('payment_intent', 'idempotency_key'), name='unique_receipt_idempotency_per_intent'),
        ),
    ]
