# Generated by Django 6.0.7 on 2026-09-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_destinationcard_paymentintent_paymentreceipt_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='pay_intent_status_created_idx',
            old_name='payment_intent_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='pay_intent_expires_idx',
            old_name='payment_intent_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreceipt',
            new_name='pay_receipt_intent_active_idx',
            old_name='payment_receipt_intent_active_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreceipt',
            new_name='pay_receipt_sha256_idx',
            old_name='payment_receipt_sha256_idx',
        ),
    ]
