# Generated by Django 6.0.7 on 2026-09-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_payment_intent_status_created_idx_pay_intent_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreview',
            name='bank_verified',
            field=models.BooleanField(default=False, verbose_name='bank verified'),
        ),
    ]
