# Generated by Django 6.0.8 on 2026-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentreview_bank_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='base_amount_rial',
            field=models.PositiveBigIntegerField(help_text='مبلغ پایه به ریال', verbose_name='base amount rial'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='payable_amount_rial',
            field=models.PositiveBigIntegerField(help_text='مبلغ پرداختی به ریال', verbose_name='payable amount rial'),
        ),
    ]
