# Generated by Django 6.0.7 on 2026-09-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_sync_model_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationcard',
            options={'verbose_name': 'کارت مقصد', 'verbose_name_plural': 'کارت\u200cهای مقصد'},
        ),
        migrations.AlterModelOptions(
            name='paymentintent',
            options={'verbose_name': 'درخواست پرداخت', 'verbose_name_plural': 'درخواست\u200cهای پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'verbose_name': 'رسید پرداخت', 'verbose_name_plural': 'رسیدهای پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='paymentreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'بررسی پرداخت', 'verbose_name_plural': 'بررسی\u200cهای پرداخت'},
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('receipt_submitted', 'رسید ارسال\u200cشده'), ('under_review', 'در حال بررسی'), ('manual_review', 'بررسی دستی'), ('paid', 'پرداخت\u200cشده'), ('rejected', 'رد شده'), ('expired', 'منقضی\u200cشده'), ('refunded', 'بازگشت وجه')], default='pending_payment', max_length=32, verbose_name='وضعیت'),
        ),
    ]
