# Generated by Django 6.0.7 on 2026-09-21 20:39

from django.conf import settings
from django.db import migrations, models


def remap_unused_statuses(apps, schema_editor):
    PaymentIntent = apps.get_model("payments", "PaymentIntent")
    PaymentReview = apps.get_model("payments", "PaymentReview")

    PaymentIntent.objects.filter(
        status__in=("under_review", "manual_review"),
    ).update(status="receipt_submitted")

    # Manual-review decisions were never written by app code; map any
    # leftover rows to rejected so choices stay consistent.
    PaymentReview.objects.filter(decision="manual_review").update(
        decision="rejected",
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_sync_model_state"),
        ("payments", "0007_sync_persian_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentintent",
            name="unique_active_payment_amount_per_card",
        ),
        migrations.RemoveConstraint(
            model_name="paymentintent",
            name="unique_active_payment_intent_per_order",
        ),
        migrations.RunPython(remap_unused_statuses, noop_reverse),
        migrations.AlterField(
            model_name="paymentintent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "در انتظار پرداخت"),
                    ("receipt_submitted", "رسید ارسال‌شده"),
                    ("paid", "پرداخت‌شده"),
                    ("rejected", "رد شده"),
                    ("expired", "منقضی‌شده"),
                    ("refunded", "بازگشت وجه"),
                ],
                default="pending_payment",
                max_length=32,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreview",
            name="decision",
            field=models.CharField(
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                max_length=32,
                verbose_name="decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending_payment", "receipt_submitted"))
                ),
                fields=("destination_card", "payable_amount_rial"),
                name="unique_active_payment_amount_per_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending_payment", "receipt_submitted"))
                ),
                fields=("order",),
                name="unique_active_payment_intent_per_order",
            ),
        ),
    ]
