# Generated by Django 6.0.7 on 2026-09-21 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentguidevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentguidevideo',
            name='video',
            field=models.FileField(blank=True, help_text='Upload an mp4/webm/mov file, or leave empty and use external URL.', upload_to='media/payments/guide', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])], verbose_name='video file'),
        ),
    ]
