# Generated by Django 6.0.7 on 2026-09-22 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_sync_admin_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentguidevideo',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='مثال: لینک آپارات، یوتیوب، یا آدرس مستقیم فایل mp4.', max_length=1000, verbose_name='لینک خارجی ویدیو'),
        ),
        migrations.AlterField(
            model_name='paymentguidevideo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد، دکمه آموزش ویدیو در صفحه پرداخت ویدیو نشان نمی\u200cدهد.', verbose_name='فعال در فروشگاه'),
        ),
        migrations.AlterField(
            model_name='paymentguidevideo',
            name='poster',
            field=models.ImageField(blank=True, help_text='اختیاری — تصویر پیش\u200cنمایش قبل از پخش.', null=True, upload_to='media/payments/guide/posters', verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='paymentguidevideo',
            name='title',
            field=models.CharField(default='آموزش پرداخت آسان', max_length=255, verbose_name='عنوان نمایشی'),
        ),
        migrations.AlterField(
            model_name='paymentguidevideo',
            name='video',
            field=models.FileField(blank=True, help_text='فرمت\u200cهای مجاز: mp4، webm، mov. اگر فایل بگذارید، لینک خارجی استفاده نمی\u200cشود.', upload_to='media/payments/guide', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])], verbose_name='فایل ویدیو'),
        ),
    ]
