# Generated by Django 6.0.7 on 2026-09-21 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_email_ci_and_primary_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphonenumber',
            options={'ordering': ['-is_primary', '-created_at'], 'verbose_name': 'شماره تلفن کاربر', 'verbose_name_plural': 'شماره\u200cهای تلفن کاربر'},
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='اصلی'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تأییدشده'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
