# Generated by Django 6.0.7 on 2026-08-03 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=20, verbose_name='Discount type')),
                ('value', models.PositiveBigIntegerField(default=0, verbose_name='Value')),
                ('minimum_order_amount', models.PositiveBigIntegerField(default=0, verbose_name='Minimum order amount')),
                ('maximum_discount_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Maximum discount amount')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited.', verbose_name='Usage limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used count')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='Per user limit')),
                ('starts_at', models.DateTimeField(verbose_name='Starts at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount', verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Discount usage',
                'verbose_name_plural': 'Discount usages',
            },
        ),
    ]
