# Generated by Django 6.0.7 on 2026-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='applies_to_discounted_products',
            field=models.BooleanField(default=True, help_text='Whether this discount can be applied to products that already have a product discount.', verbose_name='Applies to discounted products'),
        ),
    ]
