# Generated by Django 6.0.8 on 2026-09-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_discount_applies_to_discounted_products'),
        ('orders', '0007_order_public_number_and_waiting_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-created_at'], 'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='discountusage',
            options={'verbose_name': 'استفاده از تخفیف', 'verbose_name_plural': 'استفاده\u200cهای تخفیف'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='applies_to_discounted_products',
            field=models.BooleanField(default=True, help_text='آیا این تخفیف روی محصولاتی که از قبل تخفیف محصول دارند هم قابل اعمال است.', verbose_name='اعمال روی محصولات تخفیف\u200cدار'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expires_at',
            field=models.DateTimeField(verbose_name='انقضا'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='maximum_discount_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='minimum_order_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='حداقل مبلغ سفارش'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='سقف هر کاربر'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='starts_at',
            field=models.DateTimeField(verbose_name='شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='۰ یعنی نامحدود.', verbose_name='سقف استفاده'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده\u200cشده'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
