# Generated by Django 6.0.7 on 2026-08-12 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='phone number')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='is subscribed')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='subscribed at')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='unsubscribed at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'marketing subscriber',
                'verbose_name_plural': 'marketing subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
