# Generated by Django 6.0.8 on 2026-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingsubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'مشترک بازاریابی', 'verbose_name_plural': 'مشترکان بازاریابی'},
        ),
        migrations.AlterField(
            model_name='marketingsubscriber',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='عضویت فعال'),
        ),
        migrations.AlterField(
            model_name='marketingsubscriber',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='marketingsubscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='marketingsubscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو عضویت'),
        ),
    ]
