# Generated by Django 6.0.8 on 2026-09-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_sync_model_state'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'محموله', 'verbose_name_plural': 'محموله\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['price'], 'verbose_name': 'روش ارسال', 'verbose_name_plural': 'روش\u200cهای ارسال'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('returned', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='estimated_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='روزهای تخمینی'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='free_shipping_minimum',
            field=models.PositiveBigIntegerField(default=0, verbose_name='حداقل ارسال رایگان'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='عنوان'),
        ),
    ]
