# Generated by Django 6.0.7 on 2026-09-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_bugfixes_cart_discount_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='carrier',
            field=models.CharField(choices=[('post', 'پست'), ('tipax', 'تیپاکس')], default='post', max_length=16, verbose_name='حامل'),
        ),
    ]
