# Generated by Django 6.0.7 on 2026-09-11 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productvariant_volume_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='homepage_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='homepage order'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(condition=models.Q(('homepage_order__isnull', False), ('is_featured', True)), fields=('homepage_order',), name='unique_featured_homepage_order'),
        ),
    ]
