# Generated by Django 6.0.7 on 2026-09-13 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('OTP', 'OTP'), ('ORDER_CREATED', 'Order Created'), ('PAYMENT_SUCCESS', 'Payment Success'), ('NEW_CONSULTATION', 'New Consultation'), ('NEW_COMMENT', 'New Comment'), ('NEW_IMAGE', 'New Image'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_CANCELLED', 'Order Cancelled')], max_length=50)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push'), ('IN_APP', 'In App')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx'), models.Index(fields=['channel'], name='notificatio_channel_1d6e5f_idx')],
            },
        ),
    ]
