# Generated by Django 6.0.7 on 2026-09-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_in_app_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام سیستمی', 'verbose_name_plural': 'پیام\u200cهای سیستمی'},
        ),
    ]
