# Generated by Django 6.0.7 on 2026-09-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_adminalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('OTP', 'OTP'), ('ORDER_CREATED', 'Order Created'), ('PAYMENT_SUCCESS', 'Payment Success'), ('NEW_CONSULTATION', 'New Consultation'), ('NEW_COMMENT', 'New Comment'), ('NEW_IMAGE', 'New Image'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_REMINDER', 'Payment Reminder')], max_length=50),
        ),
    ]
