# Generated by Django 6.0.7 on 2026-09-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_delivery_confirm'),
        ('orders', '0012_order_delivery_confirm_sms_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='اختیاری — اگر پر شود، در اینباکس کاربر شمارندهٔ معکوس دیده می\u200cشود.', null=True, verbose_name='مهلت اقدام'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='اگر فعال باشد، اعلان در لیست خوانده\u200cشده\u200cهای کاربر قرار می\u200cگیرد.', verbose_name='خوانده\u200cشده'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='link',
            field=models.CharField(blank=True, help_text='آدرس نسبی یا کامل؛ مثلاً /orders/12 یا صفحه محصول.', max_length=512, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_app_notifications', to='orders.order', verbose_name='سفارش مرتبط'),
        ),
    ]
