# Generated by Django 6.0.7 on 2026-08-12 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_productvariant_discounted_price_less_than_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Magazine Category',
                'verbose_name_plural': 'Magazine Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='slug')),
                ('short_description', models.TextField(verbose_name='short description')),
                ('content', models.TextField(verbose_name='content')),
                ('thumbnail', models.ImageField(upload_to='media/magazines/thumbnails', verbose_name='thumbnail')),
                ('published_at', models.DateTimeField(verbose_name='published at')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='related_to', to='magazine.magazine', verbose_name='related articles')),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_magazines', to='products.product', verbose_name='related products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magazines', to='magazine.magazinecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazines',
                'ordering': ('-published_at',),
            },
        ),
    ]
