# Generated by Django 6.0.7 on 2026-08-12 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
        ('products', '0006_productvariant_discounted_price_less_than_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is_featured'),
        ),
        migrations.AddConstraint(
            model_name='magazine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('is_featured',), name='unique_featured_magazine'),
        ),
    ]
