# Generated by Django 6.0.7 on 2026-08-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_magazine_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=3, help_text='زمان تقریبی مطالعه بر حسب دقیقه', verbose_name='reading_time'),
            preserve_default=False,
        ),
    ]
