# Generated by Django 6.0.8 on 2026-09-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_magazine_reading_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ('-published_at',), 'verbose_name': 'مجله', 'verbose_name_plural': 'مجلات'},
        ),
        migrations.AlterModelOptions(
            name='magazinecategory',
            options={'ordering': ('name',), 'verbose_name': 'دسته\u200cبندی مجله', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای مجله'},
        ),
    ]
