# Generated by Django 6.0.7 on 2026-09-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_sync_model_state'),
        ('products', '0017_sync_model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magazines', to='magazine.magazinecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر شده'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='published_at',
            field=models.DateTimeField(verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=3, help_text='زمان تقریبی مطالعه بر حسب دقیقه', verbose_name='زمان مطالعه (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='magazine.magazine', verbose_name='مقالات مرتبط'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_magazines', to='products.product', verbose_name='محصولات مرتبط'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='short_description',
            field=models.TextField(verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='thumbnail',
            field=models.ImageField(upload_to='media/magazines/thumbnails', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='magazinecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='magazinecategory',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ'),
        ),
    ]
